study-me-master/config/routes.rb
Rails.application.routes.draw do
  # Devise routes
  devise_for :users, only: [
    :confirmations,
    :passwords,
    :registrations,
    :sessions
  ], controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  devise_for :participants, only: [:confirmations], controllers: {
    confirmations: 'participants/confirmations'
  }

  devise_for :researchers, only: [:confirmations], controllers: {
    confirmations: 'researchers/confirmations'
  }

  devise_scope :participant do
    patch '/participants/confirm' => 'participants/confirmations#update'
  end

  devise_scope :researcher do
    patch '/researchers/confirm' => 'researchers/confirmations#update'
  end

  # Non-standard routes
  get '/studies/search', to: 'studies#search', as: :search_studies
  get '/studies/:id/stats', to: 'studies#stats', as: :study_stats
  post '/studies/:id/timeslots/finalise', to: 'timeslots#finalise', as: :finalise_study_timeslots
  get '/payments', to: 'managed_accounts#new', as: :payments
  patch '/studies/:id/feature', to: 'studies#feature', as: :feature_study

  # Application routes
  resources :studies, only: [:index, :new, :create, :show, :update] do
    resources :participations, only: [:index, :update], controller: 'studies_participations'
    resources :non_user_participants, only: [:create]
    resources :timeslots, only: [:index, :new, :create, :destroy]
    resources :payments, only: [:create]
    resources :study_timeslots, only: [:index]
  end
  resources :managed_accounts, only: [:create]
  resources :universities, only: [:index, :new, :create]
  resources :profile, only: [:index]
  resources :participations, only: [:create, :edit, :update]
  resources :ratings, only: [:create]

  # Public routes
  get 'contact', to: 'contact#new'
  post 'contact', to: 'contact#create', as: 'contacts'

  get 'faq', to: 'faq#index', as: 'faq'
  get 'terms', to: 'terms#index', as: 'terms'
  get 'vision', to: 'vision#index', as: 'vision'

  root 'home#index'
end

study-me-master/app/models/university.rb
# University model
class University < ApplicationRecord
  include PgSearch

  has_many :researchers

  validates :domain_name, :name, :contact_name, :contact_email, :contact_number,
            :price_per_researcher, :billing_date, presence: true

  validates :billing_date, numericality: { greater_than: 0, less_than: 29 }

  validates :domain_name, format: { with: %r{[a-z0-9\-]+\.[a-z0-9\-\/\.]+},
                                    message: 'must be a valid domain name' }

  # Initialize money column properly
  monetize :price_per_researcher_pennies, with_currency: :gbp

  # Default number of universities to display per page in tables
  self.per_page = 10

  pg_search_scope :search_universities, against: [:name, :contact_name],
                                        using: { tsearch: { prefix: true } }

  # Filterrific config
  filterrific(
    default_filter_params: { sorted_by: 'name_asc' },
    available_filters: [
      :sorted_by,
      :search_query
    ]
  )

  scope :sorted_by, lambda { |sort_option|
    direction = sort_option =~ /desc$/ ? 'desc' : 'asc'

    case sort_option.to_s
    when /^name_/
      order("LOWER(universities.name) #{direction}")
    when /^added_to_study_me_/
      order("universities.created_at #{direction}")
    when /^price_per_researcher_/
      order("universities.price_per_researcher #{direction}")
    else
      raise(ArgumentError, "Invalid sort option: #{sort_option.inspect}")
    end
  }

  scope :search_query, lambda { |query|
    search_universities(query)
  }

  def next_billing_date
    date = Date.today

    date += 1.month if Date.today.day > billing_date

    date.change(day: billing_date)
  end

  def invoice_total
    price_per_researcher * researchers.count
  end
end

study-me-master/app/controllers/universities_controller.rb
# Universities controller
class UniversitiesController < PlatformController
  before_action :authenticate_admin

  def index
    @filterrific = initialize_filterrific(
      University,
      params[:filterrific],
      persistencce_id: 'shared_key',
      default_filter_params: {},
      available_filters: [:sorted_by, :search_query]
    ) || return

    @universities = @filterrific.find.page(params[:page])

    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @new_university = University.new
  end

  def create
    @new_university = University.new(new_university_params)

    if @new_university.save
      redirect_to universities_path
    else
      flash[:error] = @new_university.errors.full_messages.first
      render 'new'
    end
  end

  protected

  def new_university_params
    params.require(:university).permit(
      :name,
      :domain_name,
      :contact_name,
      :contact_email,
      :contact_number,
      :price_per_researcher,
      :billing_date
    )
  end
end

study-me-master/app/views/universities/index.html.erb
<div class="create-new-university">
<%= link_to 'Add University', new_university_path %>
</div>

<%= form_for_filterrific @filterrific do |f| %>
  <%= f.text_field :search_query, class: 'filterrific-periodically observed', placeholder: "Search" %>

  <%= link_to 'Reset filters', reset_filterrific_url, class: "reset-filters" %>
<% end %>

<div id="filterrific_results">
  <%= render(partial: 'universities/partials/list', locals: { universities: @universities }) %>
</div>

study-me-master/app/views/universities/index.js.erb
<% js = escape_javascript(render partial: 'universities/partials/list', locals: { universities: @universities }) %>
$("#filterrific_results").html("<%= js %>");
console.log("<%= js %>")

study-me-master/app/views/universities/new.html.erb
<div class="container">
  <h2>Create a new university</h2>

  <%= form_for @new_university do |f| %>
    <% if flash[:error] %>
      <div><%= format_error flash[:error] %></div>
    <% end %>

    <div class="row">
      <div class="six columns">
        <%= f.label :name, 'University name' %>
        <%= f.text_field :name, required: true %>
      </div>

      <div class="six columns">
        <%= f.label :domain_name %>
        <%= f.text_field :domain_name, required: true %>
        <p class="hint">Enter the university's domain name (e.g. "nottingham.ac.uk"), without any @ symbol, www., etc.</p>
      </div>
    </div>

    <div class="row">
      <div class="four columns">
        <%= f.label :contact_name %>
        <%= f.text_field :contact_name %>
      </div>

      <div class="four columns">
        <%= f.label :contact_email %>
        <%= f.email_field :contact_email %>
      </div>

      <div class="four columns">
        <%= f.label :contact_number %>
        <%= f.text_field :contact_number %>
      </div>
    </div>

    <div class="row">
      <div class="six columns">
        <%= f.label :price_per_researcher %>
        <%= f.number_field :price_per_researcher %>
      </div>

      <div class="six columns">
        <%= f.label :billing_date %>
        <%= f.number_field :billing_date, min: 1, max: 28, value: Date.today.day %>
        <p class="hint">Day of the month that the university will be invoiced (1-28)</p>
      </div>
    </div>

    <div class="twelve columns">
      <%= f.submit 'Save', class: 'basic button' %>
    </div>
  <% end %>
</div>