study-me-master/config/routes.rb
Rails.application.routes.draw do
  # Devise routes
  devise_for :users, only: [
    :confirmations,
    :passwords,
    :registrations,
    :sessions
  ], controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  devise_for :participants, only: [:confirmations], controllers: {
    confirmations: 'participants/confirmations'
  }

  devise_for :researchers, only: [:confirmations], controllers: {
    confirmations: 'researchers/confirmations'
  }

  devise_scope :participant do
    patch '/participants/confirm' => 'participants/confirmations#update'
  end

  devise_scope :researcher do
    patch '/researchers/confirm' => 'researchers/confirmations#update'
  end

  # Non-standard routes
  get '/studies/search', to: 'studies#search', as: :search_studies
  get '/studies/:id/stats', to: 'studies#stats', as: :study_stats
  post '/studies/:id/timeslots/finalise', to: 'timeslots#finalise', as: :finalise_study_timeslots
  get '/payments', to: 'managed_accounts#new', as: :payments
  patch '/studies/:id/feature', to: 'studies#feature', as: :feature_study

  # Application routes
  resources :studies, only: [:index, :new, :create, :show, :update] do
    resources :participations, only: [:index, :update], controller: 'studies_participations'
    resources :non_user_participants, only: [:create]
    resources :timeslots, only: [:index, :new, :create, :destroy]
    resources :payments, only: [:create]
    resources :study_timeslots, only: [:index]
  end
  resources :managed_accounts, only: [:create]
  resources :universities, only: [:index, :new, :create]
  resources :profile, only: [:index]
  resources :participations, only: [:create, :edit, :update]
  resources :ratings, only: [:create]

  # Public routes
  get 'contact', to: 'contact#new'
  post 'contact', to: 'contact#create', as: 'contacts'

  get 'faq', to: 'faq#index', as: 'faq'
  get 'terms', to: 'terms#index', as: 'terms'
  get 'vision', to: 'vision#index', as: 'vision'

  root 'home#index'
end

study-me-master/app/models/study.rb
# Study Model
class Study < ApplicationRecord
  include PgSearch

  belongs_to :researcher

  has_many :participations
  has_many :participants, through: :participations
  has_many :requirements_studies
  has_many :non_user_participants
  has_many :timeslots
  has_many :ratings

  validates :title, :aim, :reward_per_participant_pennies, :location, :duration,
            :min_age, :max_age, :gender, :number_of_participants, presence: true
  validates_length_of :aim, maximum: 1000

  # Initialize money column properly
  monetize :reward_per_participant_pennies, with_currency: :gbp

  include BackgroundPhotoAttachment
  include PDFAttachment

  # Default number of universities to display per page in tables
  self.per_page = 10

  pg_search_scope :search_studies, against: [:title],
                                   using: { tsearch: { prefix: true } }

  filterrific(
    available_filters: [
      :sorted_by,
      :search_query,
      :sorted_by_from
    ]
  )

  def self.section_is_valid?(section)
    valid_sections.include? section
  end

  def self.tags
    %w(art biology business computers environment law physics
       pyschology technology)
  end

  def self.valid_sections
    %w(tags all_studies featured_studies)
  end
  # protected_methods :valid_sections

  def add_requirements(requirements)
    requirements.each do |_key, value|
      break if value[:text] == ''

      requirement = Requirement.where('lower(text) = ?', value[:text].downcase)
                               .first

      requirement = Requirement.create(text: value[:text]) if requirement.nil?

      requirements_studies << RequirementsStudy.create(
        requirement: requirement,
        checked: value[:checked]
      )
    end

    save
  end

  def stats
    {
      genders: {
        male: participants.where(gender: 'male').count,
        female: participants.where(gender: 'female').count
      },
      ages: collect_ages,
      participations: collect_participations
    }
  end

  def accepted_participants
    participations.where(accepted: true)
  end

  def first_timeslot_complete
    timeslots.order(:to).first.to.past?
  end

  def full?
    participations.count >= number_of_participants
  end

  def joineable?
    !full? && paid && timeslots_finalised
  end

  scope :search_query, lambda { |query|
    search_studies(query)
  }

  def lowest_age
    if participants.any?
      participants.to_a.sort_by(&:age).first.age
    else
      0
    end
  end

  def highest_age
    if participants.any?
      participants.to_a.sort_by(&:age).last.age
    else
      0
    end
  end

  def mean_age
    if participants.any?
      participants.to_a.collect(&:age).sum / participants.count
    else
      0
    end
  end

  def user_can_rate_researcher?(current_user)
    participation = participations.find_by_participant_id(current_user.id)
    return false unless current_user.is_a?(Participant) && participation
    timeslot = participation.timeslot
    return false unless timeslot
    rating = Rating.where(user_id: current_user.id, study_id: id)
    return false if rating.any?
    participations.pluck(:participant_id).include?(current_user.id) &&
      DateTime.now >= timeslot.to
  end

  def total_amount_pennies
    (reward_per_participant_pennies * number_of_participants * Study.markup).to_i
  end

  def self.markup
    1.15
  end

  protected

  def collect_ages
    study_participants = participants.to_a
    ages = {}

    study_participants.collect(&:age).each do |age|
      ages[age] = study_participants
                  .select { |participant| participant.age == age }.length
    end

    ages
  end

  def collect_participations
    # p '**********************************************'
    # p accepted_participants.count == 0
    # p '**********************************************'
    return response = {} if accepted_participants.count == 0
    ordered_participations = participations.where(accepted: true)
                             .sort_by(&:created_at)

    dates_difference = ordered_participations.last.created_at - created_at

    response = if dates_difference > 1.month
                 {
                   study_me: week_by_week_participations(created_at,
                                               ordered_participations
                                               .last.created_at,
                                               ordered_participations.to_a
                                               .collect(&:created_at)),
                   external: week_by_week_participations(created_at,
                                               ordered_participations
                                               .last.created_at,
                                               non_user_participants.to_a
                                               .collect(&:recruitment_date))
                 }

               else
                 {
                   study_me: day_by_day_participations(created_at,
                                             ordered_participations
                                             .last.created_at,
                                             ordered_participations.to_a
                                             .collect(&:created_at)),
                   external: day_by_day_participations(created_at,
                                             ordered_participations
                                             .last.created_at,
                                             non_user_participants.to_a
                                             .collect(&:recruitment_date))
                 }
               end

    response
  end

  def day_by_day_participations(first_date, last_date, study_participations)
    response = {
      scale: 'day',
      dates: {}
    }

    date = first_date

    while date.to_date <= last_date.to_date
      response[:dates][date.strftime('%Y-%m-%d')] =
        study_participations
        .select { |p| p.to_date <= date }.length

      response[:dates][date.strftime('%Y-%m-%d')] ||=
        response[:dates][date - 1.day]
      date += 1.day
    end

    response
  end

  def week_by_week_participations(first_date, last_date, study_participations)
    response = {
      scale: 'week',
      dates: {}
    }

    date = first_date

    while date.to_date.strftime('%W') <= last_date.to_date.strftime('%W')
      response[:dates][date.strftime('%Y-%W')] =
        study_participations
        .select { |p| p.to_date.strftime('%W') <= date.strftime('%W') }.length

      response[:dates][date.strftime('%Y-%W')] ||=
        response[:dates][date - 1.day]
      date += 1.week
    end

    response
  end
end

study-me-master/app/controllers/studies_controller.rb
# Studies Controller
class StudiesController < PlatformController
  require 'will_paginate/array'

  before_action :authenticate_researcher, only: [:new, :create]
  before_action :authenticate_admin, only: [:feature]

  def index
    @section = params[:section]
    @section ||= 'featured_studies'
    @section_title = page_titles[@section]

    @page = params[:page]
    @page ||= 1

    if @section == 'featured_studies'
      @studies = Study.where(timeslots_finalised: true, paid: true)
                      .order(featured: :desc)
                      .paginate(page: @page, per_page: Study.per_page)
    elsif @section == 'tags' && params[:tag]
      @studies = Study.where('? = ANY (tags)', params[:tag])
                      .paginate(page: @page, per_page: Study.per_page)
    elsif @section == 'all_studies'
      @studies = Study.where(timeslots_finalised: true, paid: true)
                      .sort_by { |study| current_user.eligible?(study) ? 0 : 1 }
                      .paginate(page: @page, per_page: Study.per_page)
    end

    if @studies
      @final_page = @studies.total_pages == @page
    end

    @categories = Study.tags

    return if Study.section_is_valid? @section
    head(404)
  end

  def new
    @new_study = Study.new
  end

  def create
    @new_study = Study.new(new_study_attributes)
    @new_study.researcher = current_user
    @new_study.reward_per_participant = params[:study][:reward_per_participant]

    if @new_study.reward_per_participant == 0
      @new_study.paid = true
    end

    if @new_study.save
      @new_study.add_requirements(params[:study][:requirements_studies])
      redirect_to @new_study
    else
      # flash[:error] = @new_study.errors.first
      render :new
    end
  end

  def update
    @study = current_user.studies.find(params[:id])

    if @study.update(edit_study_params)
      flash[:success] = 'Your PDF or link has been uploaded'
      redirect_to study_path(params[:id])
    else
      flash[:error] = 'Please try uploading your PDF again'
      redirect_to study_path(params[:id])
    end

  end

  def show
    @study = Study.find(params[:id])
    @new_participation = Participation.new
    @current_user = current_user
    @new_rating = Rating.new

    if @study.researcher == current_user && !@study.timeslots_finalised
      return redirect_to new_study_timeslot_path(@study)
    end

    if @study.researcher == current_user
      @new_non_user_participant = NonUserParticipant.new

      @filterrific_participants = initialize_filterrific(
        @study.participations,
        params[:filterrific],
        persistencce_id: 'shared_key',
        default_filter_params: {},
        available_filters: [:sorted_by, :search_query]
      ) || return

      @participants_to_accept = @filterrific_participants.find.page(params[:page])

      # @filterrific_timeslots = initialize_filterrific(
      #   @study.timeslots,
      #   params[:filterrific],
      #   persistencce_id: 'shared_key',
      #   default_filter_params: {},
      #   available_filters: [:sorted_by_from]
      # ) || return
      #
      # @timeslots_view = @filterrific_timeslots.find.page(params[:page])
      
      respond_to do |format|
        format.html
        format.js
      end
    end

    return unless current_user.is_a? Participant

    @participation = @study.participations.find_by_participant_id(current_user.id)

    if @participation && !@participation.timeslot && @participation.accepted.nil?
      redirect_to edit_participation_path(@participation)
    end

    prefilled_requirements = []
    @study.requirements_studies.each do |requirement_study|
      current_user.participations.each do |participation|
        participation.participation_requirements.map { |pr|
          if pr.requirement == requirement_study.requirement
            prefilled_requirements << pr
          end
        }
      end
    end

    @reqs = {}

    Requirement.all.each do |requirement|
      r = prefilled_requirements.select { |pr| pr.requirement == requirement }
      req = r.sort_by(&:created_at).last

      @reqs[req.requirement_id] = req if req
    end
  end

  def search
    @filterrific = initialize_filterrific(
      Study,
      params[:filterrific],
      persistence_id: 'shared_key',
      available_filters: [:search_query]
    ) || return

    @studies_search_results = @filterrific.find.page(params[:page])
    @query = params[:filterrific][:search_query]

    respond_to do |format|
      format.js
      format.html
    end
  end

  def stats
    @study = Study.find_by(id: params[:id])
    return unless (current_user.is_a?(Researcher))
    return if current_user.studies.where(id: params[:id]).empty?
    @study = current_user.studies.find(params[:id])

    respond_to do |format|
      format.json { render json: @study.stats.to_json }
    end
  end

  def feature
    @study = Study.find(params[:id])
    @study.update(featured: params[:featured])
    redirect_to @study
  end

  protected

  def new_study_attributes
    params.require(:study).permit(:title, :background_photo, :aim,
                                  :number_of_participants, :location, :duration,
                                  :min_age, :max_age, gender: [], tags: [])
  end

  def edit_study_params
    params.require(:study).permit(:pdf_attachment, :study_web_link)
  end

  def page_titles
    {
      'featured_studies' => 'Featured Studies',
      'all_studies' => 'All Studies',
      'tags' => 'Categories'
    }
  end
end

study-me-master/app/views/studies/partials/_all_studies.html.erb
<% content_for :heading do %>
All
<% end %>

<% @studies.each do |study| %>
  <%= render partial: "partials/study", locals: { study: study } %>
<% end %>

study-me-master/app/views/studies/partials/_category.html.erb
<%= link_to studies_path(section: 'tags', tag: tag.downcase), class: "tag #{tag.downcase} four columns" do %>
  <%= tag %>
<% end %>

study-me-master/app/views/studies/partials/_featured_studies.html.erb
<% content_for :heading do %>
Featured Studies
<% end %>

<% @studies.each do |study| %>
  <%= render partial: "partials/study", locals: { study: study } %>
<% end %>

study-me-master/app/views/studies/partials/_non_user_participants_modal.html.erb
<div class="modal-dialog">
	<div class="modal-content">
    <%= image_tag 'icons/modal-close.png', id: 'close-modal-button', class: 'close-modal' %>
		<h2>Add a Participant Recruited from Outside Study Me</h2>
    <div class="modal-text">
      <%= form_for @new_non_user_participant, url: study_non_user_participants_path(@study), html: { class: "modal-form" }, remote: true do |f| %>
        <div id="gender-in-modal" class="row ">
          <div class="four columns center">
            <%= f.label :gender_male, class: "inline round checkbox" do %>
              <%= f.radio_button :gender, "Male" %>
              <span>Male</span>
            <% end %>
          </div>
          <div class="four columns center">
            <%= f.label :gender_female, class: "inline round checkbox" do %>
              <%= f.radio_button :gender, "Female" %>
              <span>Female</span>
            <% end %>
          </div>
          <div class="four columns center">
            <%= f.label :gender_other, class: "inline round checkbox" do %>
              <%= f.radio_button :gender, "Other" %>
              <span>Other</span>
            <% end %>
          </div>
        </div>

        <div id="dob-in-modal" class="row">
          <%= f.label :date_of_birth, "Date of birth", class:"input-field-titles" %>
          <%= f.date_field :date_of_birth, class: " ip-field-style" %>
        </div>

        <div id="mor-in-modal" class="row">
          <%= f.label :recruitment_date, "Method of Recruitment", class:"input-field-titles" %>
          <%= f.text_field :recruitment_method, autofocus: true, placeholder: "Method of Recruitment" %>
        </div>

        <div id="rd-in-modal" class="row">
          <%= f.label :recruitment_date, "Recruitment date", class:"input-field-titles" %>
          <%= f.date_field :recruitment_date, class: " ip-field-style" %>

        </div>

        <div class="row">
          <%= f.submit "Submit", id: "Modal-Submit", class: "button non-user-button" %>
        </div>
      <% end %>
    </div>
	</div>
</div>

study-me-master/app/views/studies/partials/_rate_study.html.erb
<%= form_for @new_rating do |f| %>
<div class="twelve columns">
  <h3>Please let us know how the researcher handled the study</h3>
  <h5 class="small-input-titles">How would you rate the Study?</h5>
    <%= f.hidden_field :rating, value: 0, id: 'rating' %>
    <%= f.hidden_field :study_id, value: params[:id] %>
    <%= f.hidden_field :user_being_rated_id, value: @study.researcher.id %>

    <div class="stars">
      <%= image_tag "study-stars-grey.svg" %>
      <%= image_tag "study-stars-grey.svg" %>
      <%= image_tag "study-stars-grey.svg" %>
      <%= image_tag "study-stars-grey.svg" %>
      <%= image_tag "study-stars-grey.svg" %>
    </div>
</div>
<div class="twelve columns">
  <div class="">
    <%= label_tag :notify_published_study, class: "round checkbox" do %>
      <%= check_box_tag :notify_published_study, true %>
      <span>Would you like to be notified when this study is published?</span>
    <% end %>
  </div>
</div>
<div class="twelve columns">
  <div class="center">
    <%= f.submit class:"studies-button" %>
  </div>
</div>

<% end %>

study-me-master/app/views/studies/partials/_search_list.html.erb
<ul>
  <% studies.each do |study| %>
    <li><%= link_to highlight_query(study.title, query).html_safe, study %></li>
  <% end %>
</ul>

study-me-master/app/views/studies/partials/_table_of_participants.html.erb
<% if @study.first_timeslot_complete %>
<div class="rate-participants">
  <%= link_to 'Rate Participants', study_participations_path(@study) %>
</div>
<% end %>
<table id="choose-participations" class="universities table stats">
  <thead>
    <tr>
      <th class="center-column">Name</th>
      <th class="center-column">Timeslot</th>
      <th class="center-column">Rating</th>
      <th class="center-column">Created At</th>
      <th class="center-column">Accept or Reject</th>
    </tr>
  </thead>

  <tbody>
    <% @participants_to_accept.each do |participation| %>
      <tr>
        <td><%= participation.participant.name %></td>
        <td class="center-column">
          <%  if participation.timeslot %>
            <%= human_datetime participation.timeslot.from %> - <%= human_datetime participation.timeslot.to %>
          <% elsif !participation.accepted %>
            Timeslot removed due to rejection
          <% else %>
            No timeslot yet
          <% end %>
        </td>
        <td class="center-column">
          <%= participation.participant.show_rating %>
        </td>
        <td class="center-column"><%= human_datetime participation.created_at %></td>
        <% if participation.accepted.nil? && participation.timeslot %>
          <%= form_for participation, url: study_participation_path(@study, participation), method: :patch, html: { id: 'choose-participations'} do |f| %>
            <td class="center-column">
              <%= f.label 'accepted_true', 'Accept' %>
              <%= f.radio_button :accepted, true %>
              <%= f.label 'accepted_false', 'Reject' %>
              <%= f.radio_button :accepted, false %>
            </td>
            <td class="center-column">
              <%= f.submit 'Save' %>
            </td>

          <% end %>
        <% else %>
          <td class="center-column">
            <%= participation.accepted.nil? ? 'Waiting for a timeslot' : participation.accepted ? 'Accepted' : 'Rejected'  %>
          </td>
          <td class="center-column"></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>

  <tfoot>
    <tr>
      <td colspan="6"><%= page_entries_info @participants_to_accept %></td>
      <td colspan="2"><%= will_paginate @participants_to_accept %></td>
    </tr>
  </tfoot>
</table>

study-me-master/app/views/studies/partials/_table_of_timeslots.html.erb
<table class="universities table stats timeslots-table">
  <thead>
    <tr>
      <th class="center-column">To</th>
      <th class="center-column">From</th>
      <th class="center-column">Filled</th>
    </tr>
  </thead>

  <tbody>
    <% @timeslots_view.each do |timeslot| %>
      <tr class="">
        <td class="center-column">
          <%= human_datetime timeslot.from %>
        </td>
        <td class="center-column">
          <%= human_datetime timeslot.to %>
        </td>
        <td class="center-column">
          <% if !(@study.participations.where(timeslot_id: timeslot.id).count == 0) %>
            Filled
          <% else %>
            Open
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>

  <tfoot>
    <tr>
      <td colspan="6"><%= page_entries_info @timeslots_view %></td>
      <td colspan="2"><%= will_paginate @timeslots_view %></td>
    </tr>
  </tfoot>
</table>

study-me-master/app/views/studies/partials/_tags.html.erb
<% content_for :heading do %>
  Tags
<% end %>

<% if params[:tag] %>
  <div class="row">
    <%= link_to "&lt; Back to Tags".html_safe, studies_path(section: 'tags'), class: "next page twelve columns" %>
  </div>
  <% @studies.each do |study| %>
    <%= render partial: "partials/study", locals: { study: study } %>
  <% end %>
<% else %>
  <% Study.tags.each do |tag| %>
    <%= render partial: "/studies/partials/category", locals: { tag: tag } %>
  <% end %>
<% end %>