study-me-master/config/routes.rb
Rails.application.routes.draw do
  # Devise routes
  devise_for :users, only: [
    :confirmations,
    :passwords,
    :registrations,
    :sessions
  ], controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  devise_for :participants, only: [:confirmations], controllers: {
    confirmations: 'participants/confirmations'
  }

  devise_for :researchers, only: [:confirmations], controllers: {
    confirmations: 'researchers/confirmations'
  }

  devise_scope :participant do
    patch '/participants/confirm' => 'participants/confirmations#update'
  end

  devise_scope :researcher do
    patch '/researchers/confirm' => 'researchers/confirmations#update'
  end

  # Non-standard routes
  get '/studies/search', to: 'studies#search', as: :search_studies
  get '/studies/:id/stats', to: 'studies#stats', as: :study_stats
  post '/studies/:id/timeslots/finalise', to: 'timeslots#finalise', as: :finalise_study_timeslots
  get '/payments', to: 'managed_accounts#new', as: :payments
  patch '/studies/:id/feature', to: 'studies#feature', as: :feature_study

  # Application routes
  resources :studies, only: [:index, :new, :create, :show, :update] do
    resources :participations, only: [:index, :update], controller: 'studies_participations'
    resources :non_user_participants, only: [:create]
    resources :timeslots, only: [:index, :new, :create, :destroy]
    resources :payments, only: [:create]
    resources :study_timeslots, only: [:index]
  end
  resources :managed_accounts, only: [:create]
  resources :universities, only: [:index, :new, :create]
  resources :profile, only: [:index]
  resources :participations, only: [:create, :edit, :update]
  resources :ratings, only: [:create]

  # Public routes
  get 'contact', to: 'contact#new'
  post 'contact', to: 'contact#create', as: 'contacts'

  get 'faq', to: 'faq#index', as: 'faq'
  get 'terms', to: 'terms#index', as: 'terms'
  get 'vision', to: 'vision#index', as: 'vision'

  root 'home#index'
end

study-me-master/app/models/timeslot.rb
class Timeslot < ApplicationRecord
  belongs_to :study

  has_many :participations

  validates :to, :from, presence: true

  filterrific(
  default_filter_params: { sorted_by_from: 'from_asc' },
  available_filters: [
    :sorted_by_from
  ]
  )

  scope :sorted_by_from, lambda { |sort_option|
    direction = sort_option =~ /desc$/ ? 'desc' : 'asc'

    case sort_option.to_s
    when /^from_/
      order("timeslots.from #{direction}")
    else
      raise(ArgumentError, "Invalid sort option: #{sort_option.inspect}")
    end
  }

  def is_in_future?
    from.to_date > Date.today
  end
end

study-me-master/app/controllers/timeslots_controller.rb
class TimeslotsController < PlatformController
  def index
    @study = current_user.studies.find(params[:study_id])
    # Use the provided date_from and then add 8 days to get the date to (an
    # extra day to account for this being a DateTime, so we want to get all
    # timeslots on the last day, up to 23:59)
    from = DateTime.parse(params[:page][:date_from])
    to = from + 8.days
    @timeslots = @study.timeslots
                       .where('timeslots.from >= ? AND timeslots.from < ?',
                              from, to)

    respond_to do |format|
      format.json { render json: @timeslots.to_json }
    end
  end

  def new
    @study = current_user.studies.find(params[:study_id])
    return redirect_to @study if @study.timeslots_finalised
    @number = 10
  end

  def create
    @study = current_user.studies.find(params[:study_id])
    @new_timeslot = Timeslot.new

    timeslot = params[:timeslot]
    from = DateTime.parse("#{timeslot[:date]} #{timeslot[:start_time]}")
    to = DateTime.parse("#{timeslot[:date]} #{timeslot[:end_time]}")

    return if from == to

    @new_timeslot.to = to
    @new_timeslot.from = from
    @new_timeslot.study = @study
    @new_timeslot.save

    respond_to do |format|
      format.json { render json: @new_timeslot }
    end
  end

  def destroy
    @timeslot = Timeslot.find(params[:id])

    if @timeslot.study.researcher == current_user
      @timeslot.delete
      response = { status: 204 }
    else
      response = { status: 403, error: "Forbidden" }
    end

    respond_to do |format|
      format.json { render json: response }
    end
  end

  def finalise
    @study = current_user.studies.find(params[:id])

    if @study.timeslots.count >= @study.number_of_participants
      @study.timeslots_finalised = true
      @study.save
    else
      flash[:error] = 'You must have at least as many timeslots as the number '\
                      'of participants that you have set for your study.'
    end

    redirect_to @study
  end
end

study-me-master/app/views/timeslots/new.html.erb
<div class="wrapped-div">
  <div class="cal-header">
    <div class="cal-title">
      Time Slots
      <p>Each participant will need to have a timeslot and the duration should match the duration when you created the study.</p>
      <p>Your duration = <%= @study.duration %> minutes</p>
      <p>Participants = <%= @study.number_of_participants %></p>
      <p>Click and drag to create each timeslot for each participant</p>
    </div>
    <div class="cal-week">
        <button> <i id="left-click"class="fa fa-angle-left fa-3x" aria-hidden="true"></i> </button>
        <!-- <span class="pos-middle"><%= Date::MONTHNAMES[Date.today.month] %></span> -->
        <div class="start-end-week"><span id="start-month"></span> <br /> <span id="start-day"></span></div>
        -
        <div class="start-end-week"><span id="end-month"></span> <br /> <span id="end-day"></span></div>
        <button><i id="right-click"class="fa fa-angle-right fa-3x" aria-hidden="true"></i></button>
    </div>

    <%= button_to "Submit", finalise_study_timeslots_path(@study), class: "basic button", id: "finalise_button", data: { confirm: "Are you sure? You will not be able to change the timeslots for this study after you submit them." } %>
  </div>

  <div class="cal-times">
    <div>9</div>
    <div>10</div>
    <div>11</div>
    <div>12</div>
    <div>13</div>
    <div>14</div>
    <div>15</div>
    <div>16</div>
    <div>17</div>
    <div>18</div>
    <div>19</div>
  </div>
  <hr>
  <div class="dates">
  <table>
    <tbody>
      <tr>
        <td>
          <p class="day-of-week day1">Mon</p>
          <span class="date" id="date1" data-date="-1"></span>
        </td>
        <td>
          <p class="day-of-week day2">Tue</p>
          <span class="date" id="date2"></span>
        </td>
        <td>
          <p class="day-of-week day3">Weds</p>
          <span class="date" id="date3"></span>
        </td>
        <td>
          <p class="day-of-week day4">Thurs</p>
          <span class="date" id="date4"></span>
        </td>
        <td>
          <p class="day-of-week day5">Fri</p>
          <span class="date" id="date5"></span>
        </td>
        <td>
          <p class="day-of-week day6">Sat</p>
          <span class="date" id="date6"></span>
        </td>
        <td>
          <p class="day-of-week day7">Sun</p>
          <span class="date" id="date7"></span>
        </td>
      </tr>
    </tbody>
  </table>
  </div>
  <hr>

  <div id="calender" class="calendar">
    <table id="our_table" data-study="<%= @study.id %>">
      <tbody>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td></td>

          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td></td>

          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td></td>

          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td></td>

          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
      </tbody>
    </table>

  </div>
</div>